### ISSUE TITLE
認証システム方法検討

### ISSUE THREAD

**Issue by mitohato** [mitohato/ShugakuRyokon-ServerSide#3]

**Comment by nve3pd** [comment]
`Authorization: Bearer TOKEN`

**Comment by nve3pd** [comment]
https://qiita.com/uasi/items/cfb60588daa18c2ec6f5

**Comment by mitohato** [comment]
結局、認証システムどうするんだっけ

**Comment by nve3pd** [comment]
それな...どうしよう

**Comment by ucpr** [comment]
一旦認証なしの方向で作りましょ

必要になったり良さげなやり方あったらそのときに実装する感じで

**Comment by ucpr** [comment]
@mitohato
